### ISSUE TITLE
Repeated fields are treated as invalid.

### ISSUE THREAD

**Issue by kayabaNerve** [kayabaNerve/nim-protobuf-serialization#15]
Since we don't implement the Protobuf spec language, just the binary wire protocol, we can either allow anything to be repeated (loss of detection for edge-case invalid messages) or add another pragma. I'm in favor of the first.

**Comment by kayabaNerve** [comment]
Currently, the first is implemented. Once confirmation from @zah is given, this will be closed.

**Comment by zah** [comment]
Other Nim ProtoBuf projects offer compile-time parsers for ProtoBuf files that are able to generate matching Nim type definitions. If nim-protobuf-serialization and these ProtoBuf language parsers agree on a list of pragmas that are used to map the ProtoBuf language features (e.g. such as `{.repeated.}` , then we'll be able to gain support for the entire spec eventually.

None of this is urgent to support though. For now, we should focus on the goals outlined in the original bounty.

**Comment by kayabaNerve** [comment]
Listed as an enhancement due to the small impact and low priority.

**Comment by kayabaNerve** [comment]
The fact that this test exists and passes means the expected behavior is not ocurring:
```
  test "Doesn't allow duplicate fields":
    let
      obj = Basic(a: 100, b: "Test string.", c: 'C')
      writer = ProtobufWriter.init(memoryOutput())

    writer.writeField(2, obj.b)
    writer.writeField(2, obj.b)

    expect ProtobufMessageError:
      discard Protobuf.decode(writer.finish(), type(Wrapped))
```

**Comment by kayabaNerve** [comment]
We explicitly need to always enable repeated fields.

**Comment by kayabaNerve** [comment]
We did allow repeated fields; my test was invalid. Considering the `repeated` key word refers to an array, which we support via seq, and any repeated element is valid (with the last being the actual value), this is fully compliant now.
